ARG CONFLUENTINC_VERSION=latest

FROM confluentinc/cp-server-connect-base:${CONFLUENTINC_VERSION}
RUN confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:1.8.0
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-http:latest
# RUN confluent-hub install --no-prompt jcustenborder/kafka-connect-redis:latest